# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
kotlin = "2.2.20"
kotlinLogging = "7.0.13"
mockito = "5.20.0"
mockitoKotlin = "6.1.0"
htmxSpringBoot = "5.0.0"
springBoot = "4.0.0"
shedlock = "7.3.0"
hibernateHypersistenceUtils = "3.14.0"
grpc = "1.78.0"
protobuf = "3.25.5"
coroutines = "1.9.0"
googleAuth = "1.41.0"
googleApiClient = "2.8.1"
jacksonKotlin = "2.20.1"
testcontainers = "1.20.3"

[libraries]
flywayCore = { module = "org.flywaydb:flyway-core" }
flywayDbPostgresql = { module = "org.flywaydb:flyway-database-postgresql" }
junitBom = { module = "org.junit:junit-bom", version = "5.10.0" }
junitJupiter = { module = "org.junit.jupiter:junit-jupiter" }
junitPlatformLauncher = { module = "org.junit.platform:junit-platform-launcher" }
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinLogging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlinLogging" }
mockitoAgent = { module = "org.mockito:mockito-agent", version.ref = "mockito" }
mockitoCore = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockitoJunitJupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
mockitoKotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
springBootStarter = { module = "org.springframework.boot:spring-boot-starter" }
springBootStarterActuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
springBootStarterDataJpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
springBootStarterFlyway = { module = "org.springframework.boot:spring-boot-starter-flyway" }
springBootStarterOauth2Client = { module = "org.springframework.boot:spring-boot-starter-oauth2-client" }
springBootStarterSecurity = { module = "org.springframework.boot:spring-boot-starter-security" }
springBootStarterThymeleaf = { module = "org.springframework.boot:spring-boot-starter-thymeleaf" }
springBootStarterWeb = { module = "org.springframework.boot:spring-boot-starter-web" }
springSecurityWeb = { module = "org.springframework.security:spring-security-web" }
springContext = { module = "org.springframework:spring-context" }
springSecurityOauth2Jose = { module = "org.springframework.security:spring-security-oauth2-jose" }
springTx = { module = "org.springframework:spring-tx" }
thymeleafExtrasSpringSecurity = { module = "org.thymeleaf.extras:thymeleaf-extras-springsecurity6" }
htmxSpringBoot = { module = "io.github.wimdeblauwe:htmx-spring-boot", version.ref = "htmxSpringBoot" }
htmxSpringBootThymeleaf = { module = "io.github.wimdeblauwe:htmx-spring-boot-thymeleaf", version.ref = "htmxSpringBoot" }
shedlock-spring = { module = "net.javacrumbs.shedlock:shedlock-spring", version.ref = "shedlock" }
shedlock-provider-jdbc-template = { module = "net.javacrumbs.shedlock:shedlock-provider-jdbc-template", version.ref = "shedlock" }
hypersistence-utils-hibernate = { module = "io.hypersistence:hypersistence-utils-hibernate-71", version.ref = "hibernateHypersistenceUtils" }
grpcNettyShaded = { module = "io.grpc:grpc-netty-shaded", version.ref = "grpc" }
grpcProtobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc" }
grpcStub = { module = "io.grpc:grpc-stub", version.ref = "grpc" }
protobufJava = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
kotlinCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
googleAuthLibrary = { module = "com.google.auth:google-auth-library-oauth2-http", version.ref = "googleAuth" }
googleApiClient = { module = "com.google.api-client:google-api-client", version.ref = "googleApiClient" }
springLdapCore = { module = "org.springframework.ldap:spring-ldap-core" }
jacksonDatabind = { module = "com.fasterxml.jackson.core:jackson-databind" }
jacksonKotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jacksonKotlin" }
testcontainersJunitJupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
testcontainersPostgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }

[bundles]
springContextTx = ["springContext", "springTx"]
springDataJpa = ["springBootStarterDataJpa", "hypersistence-utils-hibernate"]
springWebUi = [
    "springBootStarterWeb",
    "springBootStarterThymeleaf",
    "springBootStarterSecurity",
    "thymeleafExtrasSpringSecurity",
]
testBase = ["junitJupiter"]
testRuntime = ["junitPlatformLauncher"]
testMockito = ["mockitoCore", "mockitoJunitJupiter", "mockitoKotlin"]
htmx = ["htmxSpringBoot", "htmxSpringBootThymeleaf"]
grpc = ["grpcNettyShaded", "grpcProtobuf", "grpcStub", "protobufJava"]
jackson = ["jacksonDatabind", "jacksonKotlin"]

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
protobuf = { id = "com.google.protobuf", version = "0.9.4" }
