spring:
  messages:
    basename: admin-messages,captive-messages
  flyway:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: validate

  docker:
    compose:
      file: file:${PROJECT_ROOT:.}/app/compose.yml

app:
  locale:
    default: en
