spring:
  messages:
    basename: admin-messages,captive-messages
  flyway:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  docker:
    compose:
      file: file:${PROJECT_ROOT:.}/app/compose.yml

server:
  forward-headers-strategy: framework

app:
  locale:
    default: en
