spring:
  thymeleaf:
    cache: false
  web:
    resources:
      cache:
        period: 0
      chain:
        cache: false
  docker:
    compose:
      file: file:${PROJECT_ROOT:.}/app/compose.yml
  devtools:
    restart:
      enabled: true
      additional-paths:
        - ${PROJECT_ROOT:.}/admin
        - ${PROJECT_ROOT:.}/captive
        - ${PROJECT_ROOT:.}/shared
    livereload:
      enabled: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/wifimanager
        registration:
          admin:
            provider: keycloak
            client-id: admin-web
            client-secret: admin-web-secret
            scope:
              - openid
              - profile
              - email
              - roles
  jpa:
    show-sql: true
wifimanager:
  security:
    oidc-registration-id: admin
    authorities-provider-by-registration:
      admin: keycloak-realm-roles
  wifi:
    ssid: my-wifi
  captive:
    router-agent:
      grpc:
        port: 9091
        tls:
          enabled: false
          require-client-auth: false
      type: dummy
    auth:
      keycloak:
        enabled: true
        issuer-uri: http://localhost:8081/realms/wifimanager
        client-id: captive-portal
        client-secret: captive-portal-secret
        allowed-devices-by-role: WIFI_STAFF=1;WIFI_ADMIN=5
