spring:
  messages:
    basename: admin-messages,captive-messages
  flyway:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  docker:
    compose:
      file: file:${PROJECT_ROOT:.}/app/compose.yml

server:
  forward-headers-strategy: framework

app:
  locale:
    default: en

wifimanager:
  captive:
    auth:
      google:
        enabled: ${GOOGLE_LDAP_CAPTIVE_ENABLED:false}
        ldap-url: ldaps://ldap.google.com:636
        user-search-base: ${GOOGLE_LDAP_USER_SEARCH_BASE:}
        user-search-filter: "mail={0}"
        directory-customer: "my_customer" # use this to refer to your G Suite / Google Workspace account
        service-account-json-path: ${GOOGLE_LDAP_SERVICE_ACCOUNT_JSON:}
        impersonated-user: ${GOOGLE_LDAP_IMPERSONATED_USER:}
        directory-api-base-url: https://admin.googleapis.com/admin/directory/v1
        allowed-devices-by-group: ${GOOGLE_LDAP_ALLOWED_DEVICES_BY_GROUP:}
        connect-timeout: 5s
        read-timeout: 5s
      keycloak:
        enabled: ${KEYCLOAK_CAPTIVE_ENABLED:false}
        issuer-uri: ${KEYCLOAK_CAPTIVE_ISSUER_URI:}
        client-id: ${KEYCLOAK_CAPTIVE_CLIENT_ID:}
        client-secret: ${KEYCLOAK_CAPTIVE_CLIENT_SECRET:}
        allowed-devices-by-role: ${KEYCLOAK_CAPTIVE_ALLOWED_DEVICES_BY_ROLE:}
